'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

// Language configuration with flags and names
export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
  { code: 'da', name: 'Dansk', flag: '🇩🇰' },
  { code: 'no', name: 'Norsk', flag: '🇳🇴' },
  { code: 'fi', name: 'Suomi', flag: '🇫🇮' },
  { code: 'el', name: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'cs', name: 'Čeština', flag: '🇨🇿' },
  { code: 'hu', name: 'Magyar', flag: '🇭🇺' },
  { code: 'ro', name: 'Română', flag: '🇷🇴' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
];

// Translation keys and values - expanded for all languages
const translations: Record<string, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.area': 'Service Area',
    'nav.customers': 'Customers',
    'nav.contact': 'Contact',
    'nav.employeeLogin': 'Employee Login',
    'nav.logout': 'Logout',
    'hero.title': 'Welcome to Omni Gratum',
    'hero.subtitle': 'Professional solutions for your business',
    'about.title': 'About Us',
    'services.title': 'Services',
    'area.title': 'Service Area',
    'customers.title': 'Customers',
    'contact.title': 'Contact',
    'footer.copyright': 'All rights reserved',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.services': 'Servicios',
    'nav.area': 'Área de Servicio',
    'nav.customers': 'Clientes',
    'nav.contact': 'Contacto',
    'nav.employeeLogin': 'Inicio de Sesión de Empleados',
    'nav.logout': 'Cerrar Sesión',
    'hero.title': 'Bienvenido a Omni Gratum',
    'hero.subtitle': 'Soluciones profesionales para tu negocio',
    'about.title': 'Acerca de',
    'services.title': 'Servicios',
    'area.title': 'Área de Servicio',
    'customers.title': 'Clientes',
    'contact.title': 'Contacto',
    'footer.copyright': 'Todos los derechos reservados',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.area': 'Zone de Service',
    'nav.customers': 'Clients',
    'nav.contact': 'Contact',
    'nav.employeeLogin': 'Connexion Employé',
    'nav.logout': 'Déconnexion',
    'hero.title': 'Bienvenue chez Omni Gratum',
    'hero.subtitle': 'Des solutions professionnelles pour votre entreprise',
    'about.title': 'À Propos',
    'services.title': 'Services',
    'area.title': 'Zone de Service',
    'customers.title': 'Clients',
    'contact.title': 'Contact',
    'footer.copyright': 'Tous droits réservés',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.services': 'Leistungen',
    'nav.area': 'Einsatzgebiet',
    'nav.customers': 'Kunden',
    'nav.contact': 'Kontakt',
    'nav.employeeLogin': 'Mitarbeiter Login',
    'nav.logout': 'Abmelden',
    'hero.title': 'Willkommen bei Omni Gratum',
    'hero.subtitle': 'Professionelle Lösungen für Ihr Unternehmen',
    'about.title': 'Über uns',
    'services.title': 'Leistungen',
    'area.title': 'Einsatzgebiet',
    'customers.title': 'Kunden',
    'contact.title': 'Kontakt',
    'footer.copyright': 'Alle Rechte vorbehalten',
  },
  it: {
    'nav.home': 'Home',
    'nav.about': 'Chi Siamo',
    'nav.services': 'Servizi',
    'nav.area': 'Area di Servizio',
    'nav.customers': 'Clienti',
    'nav.contact': 'Contatti',
    'nav.employeeLogin': 'Accesso Dipendente',
    'nav.logout': 'Esci',
    'hero.title': 'Benvenuto in Omni Gratum',
    'hero.subtitle': 'Soluzioni professionali per la tua azienda',
    'about.title': 'Chi Siamo',
    'services.title': 'Servizi',
    'area.title': 'Area di Servizio',
    'customers.title': 'Clienti',
    'contact.title': 'Contatti',
    'footer.copyright': 'Tutti i diritti riservati',
  },
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.services': 'Serviços',
    'nav.area': 'Área de Serviço',
    'nav.customers': 'Clientes',
    'nav.contact': 'Contato',
    'nav.employeeLogin': 'Login de Funcionário',
    'nav.logout': 'Sair',
    'hero.title': 'Bem-vindo ao Omni Gratum',
    'hero.subtitle': 'Soluções profissionais para seu negócio',
    'about.title': 'Sobre Nós',
    'services.title': 'Serviços',
    'area.title': 'Área de Serviço',
    'customers.title': 'Clientes',
    'contact.title': 'Contato',
    'footer.copyright': 'Todos os direitos reservados',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.services': 'Услуги',
    'nav.area': 'Область обслуживания',
    'nav.customers': 'Клиенты',
    'nav.contact': 'Контакт',
    'nav.employeeLogin': 'Вход сотрудника',
    'nav.logout': 'Выход',
    'hero.title': 'Добро пожаловать в Omni Gratum',
    'hero.subtitle': 'Профессиональные решения для вашего бизнеса',
    'about.title': 'О нас',
    'services.title': 'Услуги',
    'area.title': 'Область обслуживания',
    'customers.title': 'Клиенты',
    'contact.title': 'Контакт',
    'footer.copyright': 'Все права защищены',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.about': 'について',
    'nav.services': 'サービス',
    'nav.area': 'サービスエリア',
    'nav.customers': 'お客様',
    'nav.contact': 'お問い合わせ',
    'nav.employeeLogin': '従業員ログイン',
    'nav.logout': 'ログアウト',
    'hero.title': 'Omni Gratumへようこそ',
    'hero.subtitle': 'あなたのビジネスのための専門的なソリューション',
    'about.title': 'について',
    'services.title': 'サービス',
    'area.title': 'サービスエリア',
    'customers.title': 'お客様',
    'contact.title': 'お問い合わせ',
    'footer.copyright': '著作権所有',
  },
  zh: {
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.area': '服务区域',
    'nav.customers': '客户',
    'nav.contact': '联系',
    'nav.employeeLogin': '员工登录',
    'nav.logout': '登出',
    'hero.title': '欢迎来到 Omni Gratum',
    'hero.subtitle': '为您的业务提供专业解决方案',
    'about.title': '关于我们',
    'services.title': '服务',
    'area.title': '服务区域',
    'customers.title': '客户',
    'contact.title': '联系',
    'footer.copyright': '版权所有',
  },
  ko: {
    'nav.home': '홈',
    'nav.about': '소개',
    'nav.services': '서비스',
    'nav.area': '서비스 지역',
    'nav.customers': '고객',
    'nav.contact': '연락처',
    'nav.employeeLogin': '직원 로그인',
    'nav.logout': '로그아웃',
    'hero.title': 'Omni Gratum에 오신 것을 환영합니다',
    'hero.subtitle': '귀사를 위한 전문적인 솔루션',
    'about.title': '소개',
    'services.title': '서비스',
    'area.title': '서비스 지역',
    'customers.title': '고객',
    'contact.title': '연락처',
    'footer.copyright': '저작권 소유',
  },
  ar: {
    'nav.home': 'الصفحة الرئيسية',
    'nav.about': 'معلومات عنا',
    'nav.services': 'الخدمات',
    'nav.area': 'منطقة الخدمة',
    'nav.customers': 'العملاء',
    'nav.contact': 'اتصل',
    'nav.employeeLogin': 'دخول الموظف',
    'nav.logout': 'تسجيل الخروج',
    'hero.title': 'مرحبا بك في Omni Gratum',
    'hero.subtitle': 'حلول احترافية لعملك',
    'about.title': 'معلومات عنا',
    'services.title': 'الخدمات',
    'area.title': 'منطقة الخدمة',
    'customers.title': 'العملاء',
    'contact.title': 'اتصل',
    'footer.copyright': 'جميع الحقوق محفوظة',
  },
  hi: {
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.services': 'सेवाएं',
    'nav.area': 'सेवा क्षेत्र',
    'nav.customers': 'ग्राहकों',
    'nav.contact': 'संपर्क करें',
    'nav.employeeLogin': 'कर्मचारी लॉगिन',
    'nav.logout': 'लॉग आउट',
    'hero.title': 'Omni Gratum में आपका स्वागत है',
    'hero.subtitle': 'आपके व्यवसाय के लिए पेशेवर समाधान',
    'about.title': 'हमारे बारे में',
    'services.title': 'सेवाएं',
    'area.title': 'सेवा क्षेत्र',
    'customers.title': 'ग्राहकों',
    'contact.title': 'संपर्क करें',
    'footer.copyright': 'सर्वाधिकार सुरक्षित',
  },
  pl: {
    'nav.home': 'Strona główna',
    'nav.about': 'O nas',
    'nav.services': 'Usługi',
    'nav.area': 'Obszar obsługi',
    'nav.customers': 'Klienci',
    'nav.contact': 'Kontakt',
    'nav.employeeLogin': 'Login pracownika',
    'nav.logout': 'Wyloguj się',
    'hero.title': 'Witaj w Omni Gratum',
    'hero.subtitle': 'Profesjonalne rozwiązania dla Twojej firmy',
    'about.title': 'O nas',
    'services.title': 'Usługi',
    'area.title': 'Obszar obsługi',
    'customers.title': 'Klienci',
    'contact.title': 'Kontakt',
    'footer.copyright': 'Wszystkie prawa zastrzeżone',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.area': 'Hizmet Alanı',
    'nav.customers': 'Müşteriler',
    'nav.contact': 'İletişim',
    'nav.employeeLogin': 'Çalışan Girişi',
    'nav.logout': 'Çıkış Yap',
    'hero.title': 'Omni Gratum\'a Hoşgeldiniz',
    'hero.subtitle': 'İşletmeniz için profesyonel çözümler',
    'about.title': 'Hakkımızda',
    'services.title': 'Hizmetler',
    'area.title': 'Hizmet Alanı',
    'customers.title': 'Müşteriler',
    'contact.title': 'İletişim',
    'footer.copyright': 'Tüm hakları saklıdır',
  },
  nl: {
    'nav.home': 'Thuis',
    'nav.about': 'Over ons',
    'nav.services': 'Diensten',
    'nav.area': 'Servicebereik',
    'nav.customers': 'Klanten',
    'nav.contact': 'Contact',
    'nav.employeeLogin': 'Werknemerlogin',
    'nav.logout': 'Afmelden',
    'hero.title': 'Welkom bij Omni Gratum',
    'hero.subtitle': 'Professionele oplossingen voor uw bedrijf',
    'about.title': 'Over ons',
    'services.title': 'Diensten',
    'area.title': 'Servicebereik',
    'customers.title': 'Klanten',
    'contact.title': 'Contact',
    'footer.copyright': 'Alle rechten voorbehouden',
  },
  sv: {
    'nav.home': 'Hem',
    'nav.about': 'Om oss',
    'nav.services': 'Tjänster',
    'nav.area': 'Serviceområde',
    'nav.customers': 'Kunder',
    'nav.contact': 'Kontakt',
    'nav.employeeLogin': 'Anställdlogg',
    'nav.logout': 'Logga ut',
    'hero.title': 'Välkommen till Omni Gratum',
    'hero.subtitle': 'Professionella lösningar för ditt företag',
    'about.title': 'Om oss',
    'services.title': 'Tjänster',
    'area.title': 'Serviceområde',
    'customers.title': 'Kunder',
    'contact.title': 'Kontakt',
    'footer.copyright': 'Alla rättigheter förbehållna',
  },
  da: {
    'nav.home': 'Hjem',
    'nav.about': 'Om os',
    'nav.services': 'Tjenester',
    'nav.area': 'Serviceområde',
    'nav.customers': 'Kunder',
    'nav.contact': 'Kontakt',
    'nav.employeeLogin': 'Medarbejderlogin',
    'nav.logout': 'Log ud',
    'hero.title': 'Velkommen til Omni Gratum',
    'hero.subtitle': 'Professionelle løsninger til din virksomhed',
    'about.title': 'Om os',
    'services.title': 'Tjenester',
    'area.title': 'Serviceområde',
    'customers.title': 'Kunder',
    'contact.title': 'Kontakt',
    'footer.copyright': 'Alle rettigheder forbeholdt',
  },
  no: {
    'nav.home': 'Hjem',
    'nav.about': 'Om oss',
    'nav.services': 'Tjenester',
    'nav.area': 'Serviceområde',
    'nav.customers': 'Kunder',
    'nav.contact': 'Kontakt',
    'nav.employeeLogin': 'Ansattlogging',
    'nav.logout': 'Logg ut',
    'hero.title': 'Velkommen til Omni Gratum',
    'hero.subtitle': 'Profesjonelle løsninger for din bedrift',
    'about.title': 'Om oss',
    'services.title': 'Tjenester',
    'area.title': 'Serviceområde',
    'customers.title': 'Kunder',
    'contact.title': 'Kontakt',
    'footer.copyright': 'Alle rettigheter reservert',
  },
  fi: {
    'nav.home': 'Koti',
    'nav.about': 'Tietoja meistä',
    'nav.services': 'Palvelut',
    'nav.area': 'Palvelualue',
    'nav.customers': 'Asiakkaat',
    'nav.contact': 'Ota yhteyttä',
    'nav.employeeLogin': 'Työntekijän kirjautuminen',
    'nav.logout': 'Kirjaudu ulos',
    'hero.title': 'Tervetuloa Omni Gratumiin',
    'hero.subtitle': 'Ammattimaiset ratkaisut yrityksellesi',
    'about.title': 'Tietoja meistä',
    'services.title': 'Palvelut',
    'area.title': 'Palvelualue',
    'customers.title': 'Asiakkaat',
    'contact.title': 'Ota yhteyttä',
    'footer.copyright': 'Kaikki oikeudet pidätetään',
  },
  el: {
    'nav.home': 'Αρχική Σελίδα',
    'nav.about': 'Σχετικά με ημάς',
    'nav.services': 'Υπηρεσίες',
    'nav.area': 'Περιοχή Υπηρεσίας',
    'nav.customers': 'Πελάτες',
    'nav.contact': 'Επικοινωνία',
    'nav.employeeLogin': 'Σύνδεση Υπαλλήλου',
    'nav.logout': 'Αποσύνδεση',
    'hero.title': 'Καλώς ήρθατε στο Omni Gratum',
    'hero.subtitle': 'Επαγγελματικές λύσεις για την επιχείρησή σας',
    'about.title': 'Σχετικά με ημάς',
    'services.title': 'Υπηρεσίες',
    'area.title': 'Περιοχή Υπηρεσίας',
    'customers.title': 'Πελάτες',
    'contact.title': 'Επικοινωνία',
    'footer.copyright': 'Όλα τα δικαιώματα διατηρούνται',
  },
  cs: {
    'nav.home': 'Domů',
    'nav.about': 'O nás',
    'nav.services': 'Služby',
    'nav.area': 'Oblast služby',
    'nav.customers': 'Zákazníci',
    'nav.contact': 'Kontakt',
    'nav.employeeLogin': 'Přihlášení zaměstnance',
    'nav.logout': 'Odhlásit se',
    'hero.title': 'Vítejte v Omni Gratum',
    'hero.subtitle': 'Profesionální řešení pro vaši firmu',
    'about.title': 'O nás',
    'services.title': 'Služby',
    'area.title': 'Oblast služby',
    'customers.title': 'Zákazníci',
    'contact.title': 'Kontakt',
    'footer.copyright': 'Všechna práva vyhrazena',
  },
  hu: {
    'nav.home': 'Kezdőlap',
    'nav.about': 'Rólunk',
    'nav.services': 'Szolgáltatások',
    'nav.area': 'Szolgáltatási terület',
    'nav.customers': 'Ügyfelek',
    'nav.contact': 'Kapcsolat',
    'nav.employeeLogin': 'Alkalmazott bejelentkezés',
    'nav.logout': 'Kijelentkezés',
    'hero.title': 'Üdvözöljük az Omni Gratumban',
    'hero.subtitle': 'Professzionális megoldások a vállalkozásához',
    'about.title': 'Rólunk',
    'services.title': 'Szolgáltatások',
    'area.title': 'Szolgáltatási terület',
    'customers.title': 'Ügyfelek',
    'contact.title': 'Kapcsolat',
    'footer.copyright': 'Minden jog fenntartva',
  },
  ro: {
    'nav.home': 'Acasă',
    'nav.about': 'Despre noi',
    'nav.services': 'Servicii',
    'nav.area': 'Zona de servicii',
    'nav.customers': 'Clienți',
    'nav.contact': 'Contact',
    'nav.employeeLogin': 'Autentificare angajat',
    'nav.logout': 'Deconectare',
    'hero.title': 'Bun venit la Omni Gratum',
    'hero.subtitle': 'Soluții profesionale pentru afacerea dvs',
    'about.title': 'Despre noi',
    'services.title': 'Servicii',
    'area.title': 'Zona de servicii',
    'customers.title': 'Clienți',
    'contact.title': 'Contact',
    'footer.copyright': 'Toate drepturile rezervate',
  },
  th: {
    'nav.home': 'หน้าแรก',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.services': 'บริการ',
    'nav.area': 'พื้นที่บริการ',
    'nav.customers': 'ลูกค้า',
    'nav.contact': 'ติดต่อ',
    'nav.employeeLogin': 'เข้าสู่ระบบพนักงาน',
    'nav.logout': 'ออกจากระบบ',
    'hero.title': 'ยินดีต้อนรับสู่ Omni Gratum',
    'hero.subtitle': 'โซลูชั่นมืออาชีพสำหรับธุรกิจของคุณ',
    'about.title': 'เกี่ยวกับเรา',
    'services.title': 'บริการ',
    'area.title': 'พื้นที่บริการ',
    'customers.title': 'ลูกค้า',
    'contact.title': 'ติดต่อ',
    'footer.copyright': 'สงวนสิทธิ์ทั้งหมด',
  },
  vi: {
    'nav.home': 'Trang chủ',
    'nav.about': 'Về chúng tôi',
    'nav.services': 'Dịch vụ',
    'nav.area': 'Khu vực dịch vụ',
    'nav.customers': 'Khách hàng',
    'nav.contact': 'Liên hệ',
    'nav.employeeLogin': 'Đăng nhập nhân viên',
    'nav.logout': 'Đăng xuất',
    'hero.title': 'Chào mừng đến Omni Gratum',
    'hero.subtitle': 'Giải pháp chuyên nghiệp cho doanh nghiệp của bạn',
    'about.title': 'Về chúng tôi',
    'services.title': 'Dịch vụ',
    'area.title': 'Khu vực dịch vụ',
    'customers.title': 'Khách hàng',
    'contact.title': 'Liên hệ',
    'footer.copyright': 'Bảo lưu mọi quyền',
  },
};

type Language = string;

interface LanguageContextType {
  language: Language;
  changeLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language | null;
    return savedLanguage || 'de';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['de']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
